# Makefile.common for FAST plugin

# the name of the plugin
PLUGIN_NAME = packet-fast

# the dissector sources (without any helpers)
DISSECTOR_SRC = packet-fast.c dissect.c setup.c decode.c template.c debug.c

# corresponding headers
DISSECTOR_INCLUDES = fast.h decode.h template.h

